quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:}
quarkus.datasource.password=${DB_PASSWORD:}
quarkus.datasource.jdbc.url=${DB_JDBC_URL:}

# Use 'update' or 'drop-and-create' for development; always use 'validate' or 'none' in production
quarkus.hibernate-orm.schema-management.strategy=none

# Pool Connection Settings
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.initial-size=5

# SQL Logging (useful for debugging Panache active record / repository queries)
# quarkus.hibernate-orm.log.sql=true
# quarkus.hibernate-orm.log.format-sql=true